VestrianChance: 15.2
LegendaryChance: 26.2
RareChance: 10.2
CommonItems:
  - common fire_walker_helmet
  - common fire_walker_tunic
  - common fire_walker_leggings
  - common fire_walker_boots
  - common fire_walker_elytra
  - common blessed_helm
  - common blessed_chest
  - common blessed_leggings
  - common blessed_boots
  - common blessed_elytra
  - common laborer_helm
  - common laborer_chest
  - common laborer_leggings
  - common laborer_boots
  - common laborer_elytra
  - common recruit_pick
  - common recruit_axe
  - common recruit_shovel
  - common recruit_rod
  - common recruit_hoe
  - common reforged_pick
  - common reforged_axe
  - common reforged_shovel
  - common reforged_rod
  - common reforged_hoe
  - common fortuna_pickaxe
  - common fortuna_axe
  - common fortuna_shovel
  - common fortuna_rod
  - common fortuna_hoe
  - common barbaric_falchion
  - common barbaric_bow
  - common barbaric_crossbow
  - common barbaric_battlaxe
  - common nova_sword
  - common aurora_bow
  - common eclipsed_crossbow
  - common galactic_battleaxe
  - common soldier's_sword
  - common trooper's_bow
  - common general's_crossbow
  - common legionaire's_battleaxe
RareItems:
  - rare leviathan_helm
  - rare leviathan_chest
  - rare leviathan_leggings
  - rare leviathan_boots
  - rare leviathan_wings
  - rare phoenix_helm
  - rare phoenix_plate
  - rare phoenix_leggings
  - rare phoenix_claws
  - rare phoenix_wings
  - rare mistwalker_helm
  - rare mistwalker_chest
  - rare mistwalker_leggings
  - rare mistwalker_boots
  - rare mistwalker_elytra
  - rare abyssal_pick
  - rare abyssal_axe
  - rare abyssal_shovel
  - rare abyssal_rod
  - rare abyssal_hoe
  - rare gorgon_pick
  - rare colchian_axe
  - rare cyclops_shovel
  - rare siren_rod
  - rare dryad_hoe
  - rare prophet_pick
  - rare prophet_axe
  - rare prophet_shovel
  - rare prophet_rod
  - rare prophet_hoe
  - rare sword_of_brimstone
  - rare bow_of_brimstone
  - rare crossbow_of_brimstone
  - rare battleaxe_of_brimstone
  - rare sword_of_peleus
  - rare philoctetes'_bow
  - rare crossbow_of_hephaestus
  - rare the_labrys
  - rare accursed_sword
  - rare accursed_crossbow
  - rare accursed_battleaxe
  - rare accursed_bow
LegendaryItems:
  - legendary leo's_mane
  - legendary taurus'_chest
  - legendary libra's_leggings
  - legendary pisces'_fins
  - legendary cosmic_wings
  - legendary voidwalker_helm
  - legendary voidwalker_chest
  - legendary voidwalker_legs
  - legendary voidwalker_boots
  - legendary voidwalker_wings
  - legendary helm_of_water
  - legendary chest_of_earth
  - legendary legs_of_fire
  - legendary boots_of_air
  - legendary wings_of_space
  - legendary mercury_pick
  - legendary mercury_axe
  - legendary mercury_shovel
  - legendary mercury_rod
  - legendary mercury_hoe
  - legendary eternal_pic
  - legendary eternal_axe
  - legendary eternal_shovel
  - legendary eternal_rod
  - legendary eternal_hoe
  - legendary sagittarius'_pick
  - legendary capricorn's_axe
  - legendary virgo's_shovel
  - legendary cancer's_claws
  - legendary aquarius'_hoe
  - legendary aries'_sword
  - legendary scorpio's_stinger
  - legendary gemini's_bow
  - legendary zodiac's_battleaxe
  - legendary delirium_sword
  - legendary delirium_bow
  - legendary delirium_crossbow
  - legendary delirium_battleaxe
  - legendary traveler's_sword
  - legendary traveler's_bow
  - legendary traveler's_crossbow
  - legendary traveler's_battleaxe
VestrianItems:
  - vestrian crown_of_maiele
  - vestrian tunic_of_amrynn
  - vestrian pants_of_tanyth
  - vestrian boots_of_elyon
  - vestrian wings_of_cyran
  - vestrian leviathan_gills
  - vestrian minotaur_chest
  - vestrian behemoth_leggings
  - vestrian goliath_boots
  - vestrian wings_of_the_beasts
  - vestrian helm_of_darkness
  - vestrian chest_of_the_warrior
  - vestrian leggings_of_the_storm
  - vestrian boots_of_the_sea
  - vestrian chariot_of_the_sun
  - vestrian euphoric_pick
  - vestrian euphoric_axe
  - vestrian euphoric_shovel
  - vestrian euphoric_rod
  - vestrian euphoric_hoe
  - vestrian wilds_pick
  - vestrian wilds_axe
  - vestrian wilds_shovel
  - vestrian wilds_rod
  - vestrian wilds_hoe
  - vestrian pick_of_khuguhm
  - vestrian axe_of_dhololuhr
  - vestrian shovel_of_nomam
  - vestrian rod_of_kaledur
  - vestrian hoe_of_dhomtirm
  - vestrian starfall_sword
  - vestrian starfall_bow
  - vestrian starfall_crossbow
  - vestrian starfall_battleaxe
  - vestrian firestorm_sword
  - vestrian hurricane_bow
  - vestrian cyclone_crossbow
  - vestrian typhoon_battleaxe
  - vestrian harbinger's_sword
  - vestrian harbinger's_bow
  - vestrian harbinger's_crossbow
  - vestrian harbinger's_battleaxe